# Generated by Django 5.2.6 on 2025-09-10 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_amount', models.PositiveIntegerField(help_text='cents')),
                ('amount_paid', models.PositiveIntegerField(default=0, help_text='cents')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('public_slug', models.SlugField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status'], name='finance_inv_owner_i_e6a154_idx'), models.Index(fields=['customer'], name='finance_inv_custome_8c51bd_idx'), models.Index(fields=['reference'], name='finance_inv_referen_bc8ce3_idx')],
            },
        ),
    ]
