# Generated by Django 5.2.6 on 2025-09-10 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in dollars', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('square', 'Square')], default='stripe', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Digital Wallet')], default='card', max_length=20)),
                ('external_payment_id', models.CharField(blank=True, help_text="Provider's payment ID (e.g., Stripe Payment Intent ID)", max_length=255, null=True)),
                ('external_charge_id', models.CharField(blank=True, help_text="Provider's charge ID", max_length=255, null=True)),
                ('external_refund_id', models.CharField(blank=True, help_text="Provider's refund ID", max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, help_text='Client secret for frontend', max_length=255, null=True)),
                ('payment_method_token', models.CharField(blank=True, help_text='Payment method token', max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='finance_pay_invoice_80fc36_idx'), models.Index(fields=['payment_provider', 'external_payment_id'], name='finance_pay_payment_04e4c6_idx'), models.Index(fields=['external_charge_id'], name='finance_pay_externa_02ffe0_idx'), models.Index(fields=['created_at'], name='finance_pay_created_859d0d_idx')],
            },
        ),
    ]
