# Generated by Django 5.2.6 on 2025-09-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='metadata',
        ),
    ]
