# Generated by Django 5.2.6 on 2025-09-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_invoice_amount_paid_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Refunded amount in dollars', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], help_text='Refund status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When refund was processed', null=True),
        ),
    ]
